version: '3.3'

networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: web3-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'crypto'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - app-network
  back-end:
    build: ./BackEnd
    container_name: web3-back-end
    command: npm run dev
    env_file: ./BackEnd/.env
    ports:
      - "4000:4000"
    volumes:
      - ./BackEnd:/home/node/back-end
      - /home/node/back-end/node_modules
    networks:
      - app-network
    depends_on:
      - mysql
  front-end:
    build: ./FrontEnd
    container_name: web3-front-end
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    env_file: ./FrontEnd/.env
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/home/node/front-end
      - /home/node/front-end/node_modules
    networks:
      - app-network
volumes:
  mysql-db: